safeguards added

diff --git a/runelitelauncher b/runelitelauncher
--- a/runelitelauncher
+++ b/runelitelauncher
@@ -17,31 +17,39 @@ move_directory() {
 		if [ -e ${FAKEHOME}/.runelite ]; then
 			echo "There is already a RuneLite directory in the fakehome"
 			return 1
+		else
+			echo "Attempting to move into fakehome..."
 		fi
 
 	## Taking a backup in case anything breaks
-		cp -r ${REALHOME}/.runelite ${REALHOME}/runescape.bak
+		[ -e "${REALHOME}/runelite.bak" ] && echo "There is already a backup file! You should fix this before doing anything!" && return 8
+		cp -r -- ${REALHOME}/.runelite ${REALHOME}/runelite.bak || return 7
 
 	## The thing itself
 		echo "Moving '$REALHOME/.runelite/' to '$FAKEHOME/.runelite/'"
-		mv --target-directory=$FAKEHOME -- $REALHOME/.runelite || return 1
+		mv --target-directory=$FAKEHOME -- $REALHOME/.runelite || return 2
 
 	## Cache and stuff
+		mkdir -p ${XDG_CACHE_HOME}/runelite
+
 		echo "Moving '.runelite/cache/' to '${XDG_CACHE_HOME}/runelite/runelite/'"
-		[ -d "${FAKEHOME}/.runelite/cache" ] && [ ! -e "${XDG_CACHE_HOME}/runelite/runelite" ] &&  mv -T -- $FAKEHOME/.runelite/cache ${XDG_CACHE_HOME}/runelite
+		[ -d "${FAKEHOME}/.runelite/cache" ] && [ ! -e "${XDG_CACHE_HOME}/runelite/runelite" ] &&  mv -T -- $FAKEHOME/.runelite/cache ${XDG_CACHE_HOME}/runelite/runelite
 		mkdir -p -- ${XDG_CACHE_HOME}/runelite/runelite
+		[ -e "${FAKEHOME}/.runelite/cache" ] && we_deleted_something=1 && rm -r -- ${FAKEHOME}/.runelite/cache
 		ln -sT ${XDG_CACHE_HOME}/runelite ${FAKEHOME}/.runelite/cache
 
 		echo "Moving '.runelite/jagexcache/' to '${XDG_CACHE_HOME}/runelite/runescape/'"
 		mkdir -p -- ${XDG_CACHE_HOME}/runelite
 		[ -d "${FAKEHOME}/.runelite/jagexcache" ] && [ ! -e "${XDG_CACHE_HOME}/runelite/runescape" ] && mv -T -- ${FAKEHOME}/.runelite/jagexcache ${XDG_CACHE_HOME}/runelite/runescape
 		mkdir -p -- ${XDG_CACHE_HOME}/runelite/runescape
+		[ -e "${FAKEHOME}/.runelite/jagexcache" ] && we_deleted_something=1 && rm -r -- ${FAKEHOME}/.runelite/jagexcache
 		ln -sT ${XDG_CACHE_HOME}/runelite/runescape ${FAKEHOME}/.runelite/jagexcache
 
 	## Screenshots
 		echo "Moving '.runelite/screenshots/' to '${XDG_PICTURES_DIR}/runescape/'"
 		[ -d "${FAKEHOME}/.runelite/screenshots" ] && [ ! -e "${XDG_PICTURES_DIR}/runelite" ] && mv -T -- ${FAKEHOME}/.runelite/screenshots ${XDG_PICTURES_DIR}/runelite 
 		mkdir -p -- ${XDG_PICTURES_DIR}/runelite
+		[ -e "${FAKEHOME}/.runelite/screenshots" ] && we_deleted_something=1 && rm -r -- ${FAKEHOME}/.runelite/screenshots
 		ln -sT ${XDG_PICTURES_DIR}/runelite ${FAKEHOME}/.runelite/screenshots
 
 	## Plugins and stuff
@@ -49,20 +57,25 @@ move_directory() {
 		mkdir -p -- ${XDG_DATA_HOME}/runelite
 		[ -d "${FAKEHOME}/.runelite/repository2" ] && [ ! -e "${XDG_DATA_HOME}/runelite/repository2" ] && mv -T -- ${FAKEHOME}/.runelite/repository2 ${XDG_DATA_HOME}/runelite/repository2
 		mkdir -p -- ${XDG_DATA_HOME}/runelite/repository2
+		[ -e "${FAKEHOME}/.runelite/repository2" ] && we_deleted_something=1 && rm -r -- ${FAKEHOME}/.runelite/repository2
 		ln -sT ${XDG_DATA_HOME}/runelite/repository2 ${FAKEHOME}/.runelite/repository2
 
 		echo "Moving '.runelite/plugins/' to '${XDG_DATA_HOME}/runelite/plugins/'"
 		mkdir -p ${XDG_DATA_HOME}/runelite
 		[ -d "${FAKEHOME}/.runelite/plugins" ] && [ ! -e "${XDG_DATA_HOME}/runelite/plugins" ] && mv -T -- ${FAKEHOME}/.runelite/plugins ${XDG_DATA_HOME}/runelite/plugins
 		mkdir -p -- ${XDG_DATA_HOME}/runelite/plugins
+		[ -e "${FAKEHOME}/.runelite/plugins" ] && we_deleted_something=1 && rm -r -- ${FAKEHOME}/.runelite/plugins
 		ln -sT ${XDG_DATA_HOME}/runelite/plugins ${FAKEHOME}/.runelite/plugins
 
 	## Settings and stuff
 		echo "Moving '.runelite/settings.properties' to '${XDG_CONFIG_HOME}/runelite/settings.properties'"
 		mkdir -p -- ${XDG_CONFIG_HOME}/runelite
-		[ -f "${FAKEHOME}/.runelite/settings.properties" ] && mv -T -- ${FAKEHOME}/.runelite/settings.properties ${XDG_CONFIG_HOME}/runelite/settings.properties 
+		[ -f "${FAKEHOME}/.runelite/settings.properties" ] && [ ! -e ${XDG_CONFIG_HOME}/runelite/settings.properties ] && mv -T -- ${FAKEHOME}/.runelite/settings.properties ${XDG_CONFIG_HOME}/runelite/settings.properties 
 		touch ${XDG_CONFIG_HOME}/runelite/settings.properties
+		[ -e "${FAKEHOME}/.runelite/settings.properties" ] && we_deleted_something=1 && rm -- ${FAKEHOME}/.runelite/settings.properties
 		ln -sT ${XDG_CONFIG_HOME}/runelite/settings.properties ${FAKEHOME}/.runelite/settings.properties
+
+		[ -z "${we_deleted_something}" ] && echo "It seems like all went smooth. You may want to delete ${REALHOME}/runelite.bak now. That's your responsibility." || echo "We deleted something. Compare ${REALHOME}/runelite.bak with the ${FAKEHOME}/.runelite directory, and fix it yourself"
 
 	else
 		if [ -e ${FAKEHOME}/.runelite ]; then
@@ -97,8 +110,9 @@ main() {
 	export _JAVA_OPTIONS=-Duser.home=${FAKEHOME}
 
 	move_directory 
+	errno="$?"
 
-	[ "$?" = "0" ] && java -jar -Duser.home=${FAKEHOME} $RUNELITE_EXEC "$@" || echo "Failed to fakehome runelite: "$?""
+	[ "$errno" -eq "0" ] && echo -e "We are done preparing. Launching the game...\n\n\n" && java -jar -Duser.home=${FAKEHOME} $RUNELITE_EXEC "$@" || echo "Failed to fakehome runelite: "$errno""
 }
 
 main
